### ISSUE TITLE
Incompatible with Dynamic Crosshair.

### ISSUE THREAD

**Issue by iekiekkeikei** [ItziSpyder/CrosshairTarget#1]
Dynamic Crosshair conflicts with the crosshairs in this mod.

This mod is so cool.
I would definitely use it with dynamic cross hairs!

**Comment by ItziSpyder** [comment]
> Dynamic Crosshair conflicts with the crosshairs in this mod.
> 
> This mod is so cool. I would definitely use it with dynamic cross hairs!

What even is dynamic cross hair?

**Comment by I-No-oNe** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair
@ItziSpyder

**Comment by I-No-oNe** [comment]
> ## @iekiekkeikei, do u have the crash log?

**Comment by iekiekkeikei** [comment]
Sorry, the translation didn't seem to work....

I was trying to talk about visual bugs.
Hence, no crash report.

**Comment by ItziSpyder** [comment]
excuse me for the late reply, got caught up in exams.

i can't make this mod compatible with dynamic crosshairs. they are two entirely different concepts. imagine how "interesting" a bow scope crosshair from this mod would look with a weird crosshair from another mod. 

if this is simply just compatibility, you may have to choose between the two mods. again, sorry for the inconvenience.
