### ISSUE TITLE
any way to turn the red highlight on mobs off?

### ISSUE THREAD

**Issue by memphismc** [ItziSpyder/CrosshairTarget#3]
![image](https://github.com/ItziSpyder/CrosshairTarget/assets/129392333/a3d1a364-8d56-4a19-939b-be2dd04056c3)

this causes frame drops on my end, is there a config?

**Comment by ItziSpyder** [comment]
there currently isn't a config yet.

**Comment by ItziSpyder** [comment]
removed in the new update 0.0.3, sorry for the inconvenience
