### ISSUE TITLE
 red highlight error

### ISSUE THREAD

**Issue by InvisuaL0** [ItziSpyder/CrosshairTarget#4]
How do I fix it? The red highlight is not working properly. how can I fix it or can I remove it?

![2024-03-15_22 54 47](https://github.com/ItziSpyder/CrosshairTarget/assets/163572482/b6b9d3ea-539b-45b0-b3f1-991a58eae96f)
![2024-03-15_22 55 01](https://github.com/ItziSpyder/CrosshairTarget/assets/163572482/533a98c7-3d3f-4699-9744-ba78818655fa)

**Comment by ItziSpyder** [comment]
update your game to 1.20.4

**Comment by ItziSpyder** [comment]
removed in the new update 0.0.3, thanks for reporting!
